version: '3'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: yarn start:dev api-gateway
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - postgres

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - postgres

  mongodb:
    image: mongo
    ports:
      - '27017:27017'

  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
    command:
      - 'postgres'
      - '-c'
      - 'track_commit_timestamp=on'
      - '-c'
      - 'log_destination=stderr'

networks:
  postgres:
    driver: bridge

