version: '3'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: yarn start:dev api-gateway
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - postgres

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    networks:
      - postgres

  mongodb:
    image: mongo
    ports:
      - '27017:27017'

  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres
    command:
      - 'postgres'
      - '-c'
      - 'track_commit_timestamp=on'
      - '-c'
      - 'log_destination=stderr'

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
 
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge

